# -*- coding: utf-8 -*-
"""lab2_Interactive Study Assistant.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qPYvWLHHp56jlI6C2k2kD88ZjTw5OFYK
"""

!pip install -q -U google-genai
!pip install -q gradio

from google import genai
from google.colab import userdata
import gradio as gr
client = genai.Client(api_key=userdata.get('lab2_gemini_api_key'))
def study_assistant(topic, mode):
    if mode == "Explain":
        prompt = f"Explain the following topic in a simple and easy-to-understand way for a student: {topic}"
    elif mode == "Summarize":
        prompt = f"Give a short and clear summary of the following topic: {topic}"
    else:
        prompt = f"Generate 5 quiz questions about the following topic and include the answers at the end: {topic}"
    response = client.models.generate_content(
        model="gemini-3.6-flash",
        contents=prompt
    )
    return response.text
demo = gr.Interface(
    fn=study_assistant,
    inputs=[
        gr.Textbox(lines=5, placeholder="Enter a topic or question...", label="Topic / Question"),
        gr.Radio(choices=["Explain", "Summarize", "Generate Quiz"], value="Explain", label="Study Mode")
    ],
    outputs=gr.Textbox(lines=15, label="Study Assistant Response"),
    title="Interactive Study Assistant",
    description="Enter a topic and choose how you want the Study Assistant to help you."
)
demo.launch(debug=True)